/**
 * WhatToCook.WebAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { MealPlanForDayResponse } from './mealPlanForDayResponse';

export interface PlanOfMealResponse {
  fromDate: string;
  id: number;
  name: string;
  recipes: Array<MealPlanForDayResponse>;
  toDate: string;
}
