/**
 * WhatToCook.WebAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { PlanOfMealForDay } from './planOfMealForDay';

export interface PlanOfMealRequest {
  id: number;
  fromDate: string;
  name: string;
  recipes: Array<PlanOfMealForDay>;
  toDate: string;
}
